#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

# match pubs to logos
- id: doi:10.1029/2024GL108866
  image: images/air-sea.png
  
- id: doi:10.1525/elementa.2021.00107
  image: images/exports_logo.png

- id: doi:10.1575/1912/29464
  image: images/exports_logo.png

- id: doi:10.1029/2020GB006718
  image: images/exports_logo.png

- id: https://doi.org/10.31223/X5C097
  image: images/exports_logo.png

- id: doi:10.1029/2020GB006764
  image: images/exports_logo.png

- id: doi:10.12688/openreseurope.15047.2
  image: images/gobgc-logo-2-sm.png

- id: doi:10.1029/2020GL087669
  image: images/chemyak.png

- id: doi:10.1021/acs.est.8b04190
  image: images/chemyak.png

- id: doi:10.1146/annurev-marine-121916-063604
  image: images/air-sea.png

- id: doi:10.1029/2021GB007145
  image: images/air-sea.png

- id: doi:10.1002/lno.12154
  image: images/air-sea.png

- id: doi:10.5194/bg-16-3351-2019
  image: images/air-sea.png